SocialGouv/domifa

- packages/frontend/jest.config.js
> test: make jest-preset-angular work

- .travis.yml
> ci(travis): add dummy travis.yml

- packages/frontend/.gitignore
> chore: ignore the dist folder

- .gitlab-ci.yml
- .gitlab-ci/stages/quality.yml
> ci(gitlab): move integration test

- .travis.yml
> ci(travis): fix integration tests

- .travis.yml
> ci(travis): use apt addons

- docker-compose.prod.yml
> build(docker): add restart always in production

- Dockerfile
- packages/backend/Dockerfile
> Revert "chore(deps): update node.js to v13"

- packages/frontend/src/app/modules/general/components/home/home.component.html
> fix: avatars urls

- .travis.yml
> ci(travis): remove manual code folding

- .gitlab-ci/stages/quality.yml
> ci(gitlab): do not allow lint to fail

- packages/frontend/tsconfig.json
> build(ts): add angularCompilerOptions

- packages/frontend/angular.json
> build(angular): our current build as @angular/cli hosted

- CONTRIBUTING.md
> docs(CONTRIBUTING): add some tips

- optional/e2e/runners/puppeteer/package.json
- optional/e2e/runners/puppeteer/yarn.lock
> Revert "fix(deps): update dependency puppeteer to ^5.3.0"

- packages/frontend/src/app/modules/usagers/components/manage/manage.component.ts
- packages/frontend/src/app/modules/usagers/components/manage/manage.css
- packages/frontend/src/app/modules/usagers/components/manage/manage.html
- packages/frontend/src/app/modules/usagers/interfaces/search.ts
- packages/frontend/src/app/modules/usagers/services/usager.service.ts
> feat(structure): bugs barre de recherche

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- packages/backend/src/stats/controllers/stats.controller.ts
- packages/backend/src/usagers/controllers/export.controller.ts
- packages/frontend/src/app/modules/general/components/faq/faq.component.old.html
- packages/frontend/src/app/modules/stats/components/dashboard/dashboard.component.css
- packages/frontend/src/app/modules/stats/components/dashboard/dashboard.component.html
- packages/frontend/src/app/modules/stats/components/rapport/rapport.component.html
- packages/frontend/src/app/modules/stats/components/stats/stats.component.html
- packages/frontend/src/app/modules/stats/stats.interface.ts
- packages/frontend/src/assets/files/news.json
> bug(ADMIN): [stats déploiement] problèmes d'affichage

- packages/backend/src/auth/guards/responsable.guard.ts
- packages/backend/src/users/services/mailjet.service.ts
- packages/backend/src/users/services/users.service.ts
- packages/backend/src/users/user-profil.type.ts
- packages/backend/src/users/users.controller.ts
- packages/frontend/src/app/modules/users/components/user-profil/user-profil.component.ts
- packages/frontend/src/app/modules/users/interfaces/user-profil.type.ts
- packages/frontend/src/app/modules/users/services/users.service.ts
> feat(Sécurité): limiter les données renvoyées au frontend #856

- packages/backend/src/mails/_templates/users-creation-compte-par-un-admin.html
- packages/frontend/src/app/modules/usagers/components/manage/manage.component.ts
- packages/frontend/src/app/modules/usagers/components/manage/manage.html
fix(manage): correction de l'affichage du tri
> fix(tipimail): correction des envois de mails manquants

- packages/backend/src/usagers/services/usagers.service.ts
- packages/frontend/src/app/modules/usagers/components/documents/documents.component.html
- packages/frontend/src/app/modules/usagers/components/documents/documents.component.ts
- packages/frontend/src/app/modules/usagers/components/form/usagers-form.ts
- packages/frontend/src/app/modules/usagers/components/manage/manage.component.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil-component.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil-procuration-courrier/profil-procuration-courrier-component.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil-transfert-courrier/profil-transfert-courrier-component.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil.html
- packages/frontend/src/app/modules/users/components/user-profil/user-profil.component.ts
Correction d'un bug sur la suppression de PJ
> Ajout des trackers matomo manquants

- packages/backend/src/database/entities/message-email/MessageEmailContent.type.ts
- packages/backend/src/database/entities/message-email/MessageEmailId.type.ts
- packages/backend/src/mails/services/cron-mail-import-guide-sender.service.ts
- packages/backend/src/mails/services/cron-mail-user-guide-sender.service.ts
- packages/backend/src/mails/services/domifa-mails.service.ts
- packages/backend/src/mails/services/structures-mails.service.ts
- packages/backend/src/mails/services/tipimail-sender.service.ts
- packages/backend/src/mails/services/usagers-mails.service.ts
- packages/backend/src/mails/services/users-mails.service.ts
- packages/backend/src/users/users.controller.ts
Suite https://github.com/SocialGouv/domifa/issues/1015
> feat(mail): better mail management

- packages/backend/src/excel/export-structure-usagers/worksheet-renderer/exportListeParticipantsWorksheetRenderer.ts
- packages/backend/src/usagers/controllers/export-structure-usagers.controller.ts
- packages/backend/src/usagers/controllers/usagers.controller.ts
- packages/frontend/src/app/modules/usagers/components/form/parts/decision/decision.component.ts
- packages/frontend/src/app/modules/usagers/components/form/usagers-form.ts
- packages/frontend/src/app/modules/usagers/interfaces/usager.ts
fix(interactions): correction du bug stop courrier pour le facteur
> fix(export): ajout du bon nom d'utilisateur pour les renouvellements

- packages/backend/src/database/entities/message-email/MessageEmailSendDetails.type.ts
- packages/backend/src/mails/services/tipimail-sender.service.ts
Add tipimail response data to database mails history
> feat(email): better batchs & email management #1015

- packages/frontend/src/app/modules/structures/components/structure-edit-form/structure-edit-form.component.html
- packages/frontend/src/app/modules/structures/components/structure-edit-form/structure-edit-form.component.spec.ts
- packages/frontend/src/app/modules/structures/components/structure-edit-form/structure-edit-form.component.ts
- packages/frontend/src/app/modules/structures/components/structures-edit/structures-edit.component.html
- packages/frontend/src/app/modules/structures/components/structures-edit/structures-edit.component.ts
- packages/frontend/src/app/modules/structures/components/structures-upload-docs/structures-upload-docs.component.ts
- packages/frontend/src/app/modules/structures/structures.module.ts
refacto: séparation du formulaire d'édition de la structure
> fix: édition et ajout de structure avec adresse de réception #1023

- packages/backend/package.json
- packages/backend/src/structures/controllers/structure-doc.controller.ts
- packages/frontend/package.json
- packages/frontend/src/_common/model/structure-doc/StructureDoc.type.ts
- packages/frontend/src/app/modules/structures/components/structures-upload-docs/structures-upload-docs.component.html
- packages/frontend/src/app/modules/structures/components/structures-upload-docs/structures-upload-docs.component.ts
- packages/frontend/src/app/modules/usagers/components/documents/documents.component.html
- packages/frontend/src/app/modules/usagers/components/documents/documents.component.ts
- packages/frontend/src/app/modules/usagers/components/upload/upload.component.html
- packages/frontend/src/app/modules/usagers/components/upload/upload.component.ts
- packages/frontend/src/app/modules/usagers/interfaces/doc.ts
- packages/frontend/src/app/shared/upload-validator.ts
- packages/frontend/src/assets/css/forms.css
- yarn.lock
> Clarification de l'upload et correction de bugs

- tech.yaml
https://github.com/SocialGouv/domifa/issues/1064
> feat(tech): décrire la stack technique #1064

- packages/backend/src/usagers/controllers/docs.controller.ts
- packages/frontend/src/_common/model/usager/UsagerDoc.type.ts
- packages/frontend/src/app/modules/usagers/components/documents/documents.component.html
- packages/frontend/src/app/modules/usagers/components/documents/documents.component.ts
- packages/frontend/src/app/modules/usagers/components/entretien/entretien.component.html
- packages/frontend/src/app/modules/usagers/components/entretien/entretien.component.ts
- packages/frontend/src/app/modules/usagers/components/form/parts/documents-form/documents-form.component.html
- packages/frontend/src/app/modules/usagers/components/form/parts/documents-form/documents-form.component.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil-component.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil.html
- packages/frontend/src/app/modules/usagers/components/upload/upload.component.ts
- packages/frontend/src/app/modules/usagers/services/document.service.ts
- packages/frontend/src/app/shared/upload-validator.ts
fix: la liste des documents se met à jour lors d'un upload dans une création de dossier #1169 
fix: l'entretien pour une nouvelle création de dossier (pas de ticket rédigé)
> Upload de documents + entretien

- packages/backend/src/_migrations/1614089579788-clear-etapeDemande.migration.ts
- packages/backend/src/database/entities/usager/ETAPES_DEMANDE.const.ts
- packages/backend/src/usagers/controllers/import.controller.ts
- packages/backend/src/usagers/controllers/usagers.controller.ts
- packages/backend/src/usagers/services/usagers.service.ts
- packages/frontend/src/_common/mocks/usager.mock.ts
- packages/frontend/src/_common/model/usager/ETAPES_DEMANDE.const.ts
- packages/frontend/src/app/modules/usagers/components/form/UsagerFormModel.ts
fix: suppression de l'étape 6 qui ne correspondait à rien
> fix: documentation des étapes de la demande

- packages/backend/src/_migrations/1614194657232-set-rdv-null.migration.ts
- packages/backend/src/usagers/services/usagers.service.ts
- packages/frontend/src/_common/model/usager/UsagerDecisionForm.type.ts
- packages/frontend/src/app/modules/usagers/components/form/parts/decision/decision.component.html
- packages/frontend/src/app/modules/usagers/components/form/parts/decision/decision.component.ts
- packages/frontend/src/app/modules/usagers/components/form/parts/menu/menu.component.ts
- packages/frontend/src/app/modules/usagers/components/form/parts/rdv/rdv.component.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil-component.ts
- packages/frontend/src/app/modules/usagers/components/raft/raft.component.html
- packages/frontend/src/app/modules/usagers/components/raft/raft.component.ts
- packages/frontend/src/app/modules/usagers/services/document.service.ts
- packages/frontend/src/app/modules/usagers/services/interaction.service.ts
- packages/frontend/src/app/modules/usagers/services/usager.service.ts
refacto: la partie décision a été allégée et un bug d'affichage corrigé
> fix: rendez-vous dans le futur

- packages/backend/src/auth/auth.controller.ts
- packages/backend/src/users/services/users.service.ts
fix: affichage du message vide quand le mot de passe n'a pas été défini
> fix: erreur sentry "invalid salt"

- packages/frontend/src/app/modules/stats/components/dashboard/dashboard.component.ts
> fix(STATS_DOMIFA): bouton tri colonne domiciliés ne fonctionne plus

- packages/backend/src/interactions/interactions.controller.ts
- packages/backend/src/sms/services/sms.service.ts
- packages/frontend/src/app/app.component.html
- packages/frontend/src/app/modules/structures/components/structures-sms-form/structures-sms-form.component.html
- packages/frontend/src/app/modules/structures/components/structures-sms-form/structures-sms-form.component.ts
- packages/frontend/src/app/modules/structures/services/generateSender.service.ts
- packages/frontend/src/app/modules/usagers/components/form/usagers-form.html
- packages/frontend/src/app/modules/usagers/components/form/usagers-form.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil-edit-preference/profil-edit-preference.component.html
- packages/frontend/src/app/modules/usagers/components/profil/profil-edit-preference/profil-edit-preference.component.ts
fix(sms): correction des bugs sur le formulaire de création de demande
> feat(sms): ajout d'un tableau pour la review PO

- packages/backend/src/_common/model/message-sms/MessageSms.type.ts
- packages/backend/src/database/entities/message-sms/MessageSmsTable.typeorm.ts
- packages/backend/src/database/services/message-sms/messageSmsRepository.service.ts
- packages/backend/src/interactions/interactions.controller.ts
- packages/backend/src/interactions/interactions.service.ts
- packages/backend/src/sms/services/sms.service.ts
- packages/backend/src/usagers/dto/preferenceContact.dto.ts
- packages/frontend/src/app/app-routing.module.ts
- packages/frontend/src/app/guards/can-edit-sms.guard.ts
- packages/frontend/src/app/modules/stats/components/dashboard/dashboard.component.ts
- packages/frontend/src/app/modules/structures/components/structures-sms-form/structures-sms-form.component.html
- packages/frontend/src/app/modules/usagers/components/form/usagers-form.html
- packages/frontend/src/app/modules/usagers/components/profil/profil-edit-preference/profil-edit-preference.component.html
- packages/frontend/src/app/modules/usagers/components/profil/profil-edit-preference/profil-edit-preference.component.ts
- packages/frontend/src/app/modules/usagers/services/usager.service.ts
> Fix: correction des bugs sur les préférences des SMS 

- packages/backend/src/_static/email-templates/user-account-activated/html.nunjucks
- packages/backend/src/_static/email-templates/user-account-activated/test.ref.html
- packages/backend/src/_static/email-templates/user-account-activated/text.nunjucks
- packages/backend/src/config/domifaConfig.service.ts
- packages/backend/src/sms/services/sms.service.ts
- packages/frontend/src/app/app.component.html
- packages/frontend/src/app/interceptors/server-error.interceptor.ts
- packages/frontend/src/app/modules/shared/services/auth.service.ts
- packages/frontend/src/app/modules/structures/components/structures-sms-form/structures-sms-form.component.html
- packages/frontend/src/app/modules/structures/components/structures-sms-form/structures-sms-form.component.ts
- packages/frontend/src/app/modules/usagers/components/form/parts/decision/decision.component.html
- packages/frontend/src/app/modules/usagers/components/manage/manage.component.ts
feat(sms): correction du timing d'envoi
feat(sms): correction de l'affichage de l'heure d'envoi
> feat(mails): ajout des infos pour les formations sur l'email de compte activé

- packages/frontend/src/app/modules/usagers/components/manage/manage.component.ts
- packages/frontend/src/environments/environment.prod.ts
> fix(requetes): rafraichissement en boucle si déconnecté

- packages/backend/src/health/health.controller.ts
- packages/frontend/src/app/modules/shared/services/health-check/health-check.service.ts
> feat(healthcheck): séparer healthcheck back & front #1355

- packages/backend/src/usagers/controllers/usagers.controller.ts
- packages/backend/src/usagers/services/usagerVisibleHistoryManager.service.ts
- packages/frontend/src/app/modules/usagers/services/usager.service.ts
https://github.com/SocialGouv/domifa/issues/1422
> fix: supression demande renouvellement

- packages/frontend/package.json
- packages/frontend/src/app/modules/usagers/components/manage/manage.component.ts
- packages/frontend/src/app/modules/usagers/services/usager.service.ts
- packages/frontend/src/app/shared/store/AppStoreAction.type.ts
- packages/frontend/src/app/shared/store/AppStoreModel.type.ts
- packages/frontend/src/app/shared/store/appStore.service.ts
- packages/frontend/src/app/shared/store/index.ts
- packages/frontend/src/app/shared/store/usagersSearchCache.service.spec.ts
- packages/frontend/src/app/shared/store/usagersSearchCache.service.ts
- yarn.lock
https://github.com/SocialGouv/domifa/issues/1416
> feat: basic cache for usagers search

- .gitlab-ci.yml
- packages/frontend/Dockerfile
- packages/frontend/nginx.conf
> fix: update nginx config #995 #996

- packages/frontend/src/app/modules/usagers/components/interactions/set-interaction-out-form/set-interaction-out-form.component.html
- packages/frontend/src/app/modules/usagers/components/interactions/set-interaction-out-form/set-interaction-out-form.component.ts
feat(MAQUETTE_DESIGN): nouveau système de courriers - Part 1 #1262
> fix: affichage des contenus de message

- _scripts/sql/find_emails_by_address.sql
- packages/frontend/src/app/modules/structures/components/register-user/register-user.component.ts
- packages/frontend/src/app/modules/usagers/components/form/usagers-form.html
- packages/frontend/src/app/modules/usagers/components/form/usagers-form.ts
- packages/frontend/src/app/modules/usagers/components/profil/profil.old.html
- packages/frontend/src/app/shared/constants/LANGUAGES.const.ts
- packages/frontend/src/app/shared/languages-autocomplete.util.ts
https://github.com/SocialGouv/domifa/issues/1462
> fix(LANGUE_PARLEE): improve language picker

- packages/frontend/src/app/modules/usagers/components/manage/manage.component.ts
- packages/frontend/src/app/modules/usagers/components/manage/manage.html
https://github.com/SocialGouv/domifa/issues/1477
> fix: label tri domicilies

- .github/renovate.json
\fw https://github.com/SocialGouv/renovate-config/blob/master/renovate.json#L5-L11
> chore(renovate): start merging socialgouv config

- packages/backend/src/interactions/services/InteractionsDeletor.service.ts
- packages/backend/src/interactions/services/InteractionsSmsManager.service.ts
- packages/backend/src/sms/services/message-sms.service.ts
- packages/frontend/src/app/modules/usagers/services/usager.service.ts
> fix(interactions): mise à jour du SMS seulement pour les interactions entrantes

- .github/workflows/release.yml
> fix(github): release commit as @SocialGroovyBot

- .github/renovate.json
\see https://github.com/SocialGouv/renovate-config/blob/master/renovate.json#L13-L16
>  chore(renovate): start merging socialgouv config (2)

- .github/workflows/production.yml
- .github/workflows/review.yml
- .k8s/components/backend.ts
- .k8s/components/frontend.ts
This reverts commit b59aefccf2bf50ee061338fff43ed2f7d9f74b1e.
> fix: Revert push to Harbor registry

- packages/backend/src/usagers/controllers/import/step2-validate-row/schema/UsagersImportUsagerSchema.yup.dates.test.ts
- packages/backend/src/usagers/controllers/import/step2-validate-row/schema/UsagersImportUsagerSchema.yup.ts
- packages/frontend/package.json
- packages/frontend/src/_common/model/usager/UsagerEcheanceInfos.type.ts
- packages/frontend/src/app/modules/structures/components/structures-sms-form/structures-sms-form.component.css
- packages/frontend/src/app/modules/structures/components/structures-sms-form/structures-sms-form.component.html
- packages/frontend/src/app/modules/usager-profil/components/profil-general-notes/profil-general-notes.component.html
- packages/frontend/src/app/modules/usager-profil/components/profil-general-section/profil-general-section.component.html
- packages/frontend/src/app/modules/usager-profil/components/profil-head/profil-head.component.ts
- packages/frontend/src/app/modules/usagers/components/manage/manage-usagers-table/manage-usagers-table.css
- packages/frontend/src/app/modules/usagers/interfaces/getEcheanceInfos.service.spec.ts
- packages/frontend/src/app/modules/usagers/interfaces/getEcheanceInfos.service.ts
- packages/frontend/src/app/modules/usagers/interfaces/getRdvInfos.service.spec.ts
- packages/frontend/src/app/modules/users/components/user-profil/user-profil.component.html
- yarn.lock
fix(profil: Affichage des badges colorés selon le niveau du dossier
> fix(import): Ajout d'une restriction pour les refus

- .k8s/environments/prod/backend.configmap.yaml
A déployer ce soir avant/après (?) la MEP
> feat(k8s): enable sms & mail to PROD

- .k8s/yarn.lock
- optional/e2e/runners/puppeteer/yarn.lock
- yarn.lock
Reverts SocialGouv/domifa#2181
> Revert "chore(deps): lock file maintenance"

- .k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap
- .k8s/package.json
- .k8s/yarn.lock
upgrade metabase vers la 0.42.4
> fix: upgrade metabase

- .github/workflows/preproduction.yml
- .github/workflows/production.yml
- .github/workflows/review.yml
- .kube-workflow/values.yaml
trailing slash is needed in urls
> fix(ci): add trailing-slashes in url variables

- .github/workflows/codeql.yaml
Ajout d'un workflow CodeQL
Résultats : https://github.com/SocialGouv/domifa/security/code-scanning?query=is%3Aopen+pr%3A2316
> chore: add CodeQL workflow

- .kube-workflow/prod/values.yaml
Metabase même si débranché de la BDD, était encore déployé. my bad
> fix(ci): disable prod metabase

- packages/backend/src/_migrations/1667855065590-updateCorruptedInteractions-migration.ts
- Correction du nombre de courriers distribués du 16 au 17 Novembre
- Recomptage de tous les courriers en attente des dossiers impactés
> Correction des interactions mal enregistrées

- packages/backend/package.json
- packages/backend/src/config/domifaConfig.service.ts
- packages/backend/src/config/model/DomifaConfig.type.ts
- packages/backend/src/usagers/controllers/usager-docs.controller.ts
- packages/backend/src/usagers/cron/migrate-files-cron.service.ts
- yarn.lock
PR pour compléter le travail effectué dans https://github.com/SocialGouv/domifa/pull/2675
> fix: update from suggestions

- packages/backend/Dockerfile
- packages/frontend/Dockerfile
Reduce backend docker image size and use newer debian
> fix: dockerfile

- .kontinuous/values.yaml
j'ai testé cette fois, my bad :)
> fix(k8s): fix resources

- .kontinuous/env/prod/values.yaml
Set requests, limits on portal-admin and portal-usages
Remove autoscaling to use the default setup (min = 2, max = 10)
> fix : addResources

- packages/frontend/src/app/app.component.html
Correction du texte : conditions généréles d'utilisation en conditions **générales** d'utilisation
> Fix : Update app.component.html

- packages/portail-usagers/src/app/modules/general/components/_static/mentions-legales/mentions-legales.component.html
Mise à jour des mentions légales notamment sur le nouveau nom du ministère et l'adresse postale.
> Fix: Update mentions-legales.component.html
